cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('my-cart/', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),

]

e_commerce_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('search/', include('search.urls')),
    path('cart/', include('cart.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('', views.search_result, name='search_result')
]

website/urls.py
from django.urls import path
from . import views


app_name = 'website'


urlpatterns = [
    path('', views.all_prod_cat, name='home'),
    path('category/<slug:cat_slug>/', views.all_prod_cat, name='products_by_category'),
    path('category/<slug:cat_slug>/<slug:prod_slug>/', views.product_detail, name='product_detail'),
]

cart/models.py
from django.db import models
from website.models import Product  # type: ignore

# Create your models here.


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id


class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product

search/models.py
from django.db import models

# Create your models here.

website/models.py
from django.db import models
from django.urls import reverse

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ["name"]
        verbose_name = "category"
        verbose_name_plural = "categories"

    def get_url(self):
        return reverse('website:products_by_category', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'product'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('website:product_detail', args=[self.category.slug, self.slug])

    def __str__(self):
        return self.name

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from website.models import Product  # type: ignore
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

# Create your views here.


def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart


def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(cart_id=_cart_id(request))
        cart.save()

    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(product=product, quantity=1, cart=cart)
        cart_item.save()

    return redirect('cart:cart_detail')


def cart_detail(request, total=0, counter=0, cart_items=None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for item in cart_items:
            total += (item.product.price * item.quantity)
            counter += item.quantity

    except ObjectDoesNotExist:
        pass

    return render(request, 'cart.html', dict(cart_items=cart_items, total=total, counter=counter))


def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()

    return redirect('cart:cart_detail')


def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()

    return redirect('cart:cart_detail')

search/views.py
from django.shortcuts import render
from website.models import Product  # type: ignore
from django.db.models import Q

# Create your views here.


def search_result(request):
    product = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

website/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, InvalidPage

# Create your views here.


def all_prod_cat(request, cat_slug=None):
    cat_page = None
    products_list = None
    if cat_slug is not None:
        cat_page = get_object_or_404(Category, slug=cat_slug)
        products_list = Product.objects.all().filter(category=cat_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)

    paginator = Paginator(products_list, 6)

    try:
        page = int(request.GET.get('page', 1))
    except:
        page = 1

    try:
        products = paginator.page(page)
    except(EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, 'category.html', {'category': cat_page, 'products': products})


def product_detail(request, cat_slug, prod_slug):
    try:
        product = Product.objects.get(category__slug=cat_slug, slug=prod_slug)

    except Exception as e:
        raise e

    return render(request, 'product.html', {'product': product})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href=" {% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&family=Roboto+Mono:wght@300;400;500;700&display=swap" rel="stylesheet">
    
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/b040b70f9a.js" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>
{% include 'header.html' %}

{% block body %}
{% endblock %}

{% include 'footer.html' %}

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/cart.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}

This is the cart page. Proceed to review your items and Place Order.

{% endblock %}


{% block title %}

Cart - OneKart

{% endblock %}


{% block body %}

{% if not cart_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center">
            Cart is Empty.
        </h1>
        <br>
        <p class="text-center">
            <a href="{% url 'website:home' %}">Continue Shopping</a>
        </p>
    </div>

</div>
{% else %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center">
            Your Cart
        </h1>
        <br>
    </div>
</div>
<div class="row mx-auto">
    <div class="col-12 col-sm-12 col-md-12 col-lg-7 text-center">
        <table class="table">
            <thead class="table-success">
            <tr>
                <th colspan="5">Your Items</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart_items %}
            <tr>
                <td>
                    <a href="item.product.get_absolute_url">
                        <img
                             src="{{ item.product.image.url }}"
                             alt="{{ item.product.name }}"
                             style="width: 100px; height: 200px;">
                    </a>
                </td>
                <td class="text-left">
                    <h2>{{ item.product.name }}</h2>
                    <br>
                    Price: ₹{{ item.product.price }}
                    <br>
                    Qty : {{ item.quantity }} x {{ item.product.name }}
                </td>
                <td>
                    {{ item.sub_total }}
                </td>
                {% if item.quantity < item.product.stock %}
                <td><a href="{% url 'cart:add_cart' item.product.id %}"><i class="fa-solid fa-plus"></i></a>
                    &nbsp;<a href="{% url 'cart:cart_remove' item.product.id %}"><i class="fa-solid fa-minus"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' item.product.id %}"><i class="fa-solid fa-trash"></i></a>
                </td>
                {% else %}
                <td>
                    <a href="{% url 'cart:cart_remove' item.product.id %}"><i class="fa-solid fa-minus"></i></a>
                    &nbsp;<a href="{% url 'cart:full_remove' item.product.id %}"><i class="fa-solid fa-trash"></i></a>
                </td>
                {% endif %}
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="col-12 col-sm-12 col-md-12 col-lg-5 text-center">
        <table class="table">
            <thead class="table-success">
            <tr>
                <th>Checkout</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    Please review your cart items before proceeding with the order payment.
                </td>
            </tr>
            <tr>
                <td><strong>Your Total : {{ total }}</strong></td>
            </tr>
            </tbody>
        </table>
        <div class="mx-auto">
            <a href="{% url 'website:home' %}" class="btn btn-primary">Continue Shopping</a>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

templates/category.html
{% extends 'base.html' %}


{% load static %}

{% block metadescription %}

{% if category %}
{{ category.description|truncatewords:155 }}
{% else %}
Welcome to OneKart. Your One-Stop for Everything.
{% endif %}

{% endblock %}


{% block title %}

{% if category %}
{{ category.name }} - OneKart
{% else %}
Welcome to OneKart.
{% endif %}

{% endblock %}


{% block body %}

<div>

    {% if category %}
    <div>
        <img src="{{ category.image.url }}" alt="{{ category.name }}" width="1350px" height="600px">
    </div>
    <br>
    <div>
        <h1>{{ category.name }}</h1>
        <p>{{ category.description }}</p>
        <hr>
    </div>
    {% else %}
    <div>
        <img src="{% static 'image/banner.png' %}" alt="banner image" width="1350px" height="">
    </div>
    <br>

    <hr>

    {% endif %}

</div>

<div class="product-container container">

    <h1>All Products</h1>

    <div class="row text-center mx-auto">

        {% for product in products.object_list %}
        <div class="products-col text-center col-md-4 mx-auto">

            <a href="{{ product.get_url }}">
                <div class="product card shadow" style="width: 18rem;">

                    <div>
                        <img class="product-img card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}">
                    </div>
                    <div class="card-body">
                        <h4>{{ product.name }}</h4>
                        <div class="card-footer">
                            <h5>₹{{ product.price }}</h5>
                        </div>
                    </div>

                </div>
            </a>
        </div>

        {% endfor %}

    </div>

    <hr>
    
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <div class="text-center">
            {% for page in products.paginator.page_range %}
            <a href="?page={{ page }}" class="btn btn-light btn-sm {% if products.number == page %} active {% endif %}">
                {{ page }}
            </a>
            {% endfor %}
        </div>
        {% endif %}
    </div>

    <hr>

</div>

{% endblock %}

templates/footer.html
<footer>
<div class="footer text-center">
    <p class="footer-text">CONTACT US</p>
    <div>
        <a href=""><i class="contact-icon fa-brands fa-instagram"></i></a>
        <a href=""><i class="contact-icon fa-brands fa-facebook"></i></a>
        <a href=""><i class="contact-icon fa-brands fa-twitter"></i></a>
    </div>
    <p class="footer-text"><i class="fa-regular fa-copyright"></i>2022 OneKart</p>
</div>
</footer>

templates/header.html
{% load static %}

<nav class="navbar navbar-dark navbar-expand-lg bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'website:home' %}"><img src="{% static 'image/logo.png' %}" alt="Logo Image" style="width: 50px;"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'website:home' %}">Home</a>
                </li>
                {% if item_count > 0 %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i>({{ item_count }})</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'cart:cart_detail' %}"><i class="fa-solid fa-cart-shopping"></i></a>
                </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        All Categories
                    </a>

                    <ul class="dropdown-menu">
                        {% for cat in links %}
                        <li><a class="dropdown-item" href="{{ cat.get_url }}">{{ cat }}</a></li>
                        {% endfor %}
                    </ul>

                </li>
            </ul>
            <form class="d-flex" action="{% url 'search:search_result' %}" method="GET" role="search">
                <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-light" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
            </form>
        </div>
    </div>
</nav>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Welcome</h1>
</body>
</html>

templates/product.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}

{{ product.description|truncatewords:155 }}

{% endblock %}


{% block title %}

{{ product.name }} - OneKart

{% endblock %}


{% block body %}

<div>
    <p>
        <a href="{% url 'website:home' %}">Home</a> |
        <a href="{{ product.category.get_url }}">{{ product.category }}</a>
        <hr>
    </p>
</div>
<br>
<div class="product-page container">
    <div class="row">
        <h1>{{ product.name }}</h1>
        <p>₹{{ product.price }}</p>
        <hr>
        <div class="card shadow col-md-4">
            <div>
                <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}">
            </div>
        </div>
        <div class="col-md-8">
            <div class="product-description">

                <h4>Product Description</h4>
                <p>{{ product.description }}</p>
                {% if product.stock <= 0 %} <p><b>Out of Stock</b></p>
                    {% else %}
                    <a class="btn btn-primary" href="{% url 'cart:add_cart' product.id %}">Add to Cart</a>
                    {% endif %}
            </div>
        </div>

    </div>
</div>

{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block metadescription %}

OneKart - Your One Stop for Everything.

{% endblock %}


{% block title %}

Search - OneKart

{% endblock %}


{% block body %}
<div class="product-container container">

<div>
    <p class="my_search_text text-center">
        You have searched for <b>{{ query }}</b>.
    </p>
</div>

    <h1>All Products</h1>

    <div class="row mx-auto">

        {% for product in products %}
        <div class="products-col text-center col-md-4 mx-auto">

            <a href="{{ product.get_url }}">
                <div class="product card shadow" style="width: 18rem;">

                    <div>
                        <img class="product-img card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}">
                    </div>
                    <div class="card-body">
                        <h4>{{ product.name }}</h4>
                        <div class="card-footer">
                            <h5>₹{{ product.price }}</h5>
                        </div>
                    </div>

                </div>
            </a>
        </div>

            {% empty %}
            <div class="row mx-auto">
                <p class="my_search_text">0 Results Found for <b>{{ query }}</b>.</p>
            </div>

        {% endfor %}

    </div>

</div>

{% endblock %}